spring:
  profiles:
    active: 
      - dev
---
server:
  port: 8002

spring:
  profiles: manage-web
  application:
    name: springcloud-gmall-manage-web
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: springcloud-gmall-manage-web
info:
  app.name: springcloud-gmall-manage-web
  company.name: www.dongfang.com
  build.artifactId: springcloud-gmall-manage-web
  build.version: 0.0.1-SNAPSHOT

---
server:
  port: 9002
  
spring:
  profiles: manage-service
  activemq:
    broker-url: tcp://192.168.255.140:61616
  application:
    name: springcloud-gmall-manage-service
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/springcloudgmall?serverTimezone=UTC&useSSL=false
  redis:
    database: 0
    host: 192.168.255.140
    port: 6379
    password: xyd1314521

activemq:
  listener:
    enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: springcloud-gmall-manage-service

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

info:
  app.name: springcloud-gmall-manage-service
  company.name: www.dongfang.com
  build.artifactId: springcloud-gmall-manage-service
  build.version: 0.0.1-SNAPSHOT
